### ISSUE TITLE
making use of free threading

### ISSUE THREAD

**Issue by jsbueno** [xiru/pysul-2024-talk#1]
After a quick look, tehre was being no gain at all with the free-threading versions.

I re-run the fib.py here, maing 2 changes:
using a "home made"  "timeit"  (it may be it is adding extra locks, forcing some synchronizations
in order to be accurate, I don´t know)  - and added a line to retrieve the results
of the created futures.

After doing that, I got a total-execution time reduction proportional to the
number of physical cores the machine I tested have:

```python
import time

def mytimeit(func):
    def wrapper(*args):
        start = time.monotonic()
        result = func(*args)
        ellapsed = time.monotonic() - start
        print(f"Ellapsed time, 1 run: {ellapsed}")
        return result
    return wrapper

# https://discuss.python.org/t/about-free-threading-performance/54604/1
def fib(n):
    if n < 3:
        return n
    return fib(n-1) + fib(n-2)

@mytimeit
def run():
    for _ in range(10):
        fib(35)

@mytimeit
def run_threads():
    from concurrent.futures import ThreadPoolExecutor, as_completed
    with ThreadPoolExecutor(max_workers=10) as executor:
        t = set()
        for _ in range(10):
            t.add(executor.submit(fib, 35))
        o = [task.done for task in as_completed(t)]


run()
print(',', end='')
run_threads()
print('')
```

**Comment by xiru** [comment]
Looks like you are right @jsbueno . I did some local testing on 3.13 with some changes in the time module usage and I have something like:

$ /opt/python/python-3.13.0rc1-ft/bin/python3.13 fib2.py
Ellapsed time, 1 run: 19.574099046999947
,Ellapsed time, 1 run: 2.211148380000054

Clearly, the methods from time module I was using are not working as expected.
